image: Visual Studio 2017

build:
  project: Manatee.Trello.sln

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

before_build:
 - nuget restore Manatee.Trello.sln
 - dotnet restore Manatee.Trello.sln
 - git submodule update --init

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
